### ISSUE TITLE
question about status

### ISSUE THREAD

**Issue by iay** [xmunoz/bugzilla2gitlab#1]
This is more a question than a direct issue. Is the project as committed to GitHub actually functional? I have come across a couple of things that appear to prevent it from working at all, so I am wondering whether perhaps there are other changes you haven't committed.

* Dry run being set when pulling user IDs means that loading user IDs never succeeds
* typo `reponse` instead of `response` results in a `NameError` when pulling from Bugzilla

I can put in issues and PRs for these and anything else I find, I'd just like to know whether the code was ever functional so that I know whether it's worth pursuing.

**Comment by xmunoz** [comment]
Yes, this code has been used for a migration, but I did perform some cleanup at the end that may have resulted in some typos. PR's are more than welcome, sorry about the bugs!

**Comment by iay** [comment]
I know how that cleanup thing goes. It looks like your commit does essentially the same thing as my PR would have, so no need for that now.

I have been able to run the first batch of the migration I am working on, so it looks like everything is functional at this stage. I will open a new ticket if I come across something else.

Thanks!

**Comment by xmunoz** [comment]
Thank you! And let me know if you run into any more problems. Every time a software project moves away from bugzilla, an angel gets its wings!
