### ISSUE TITLE
How to run the script to make the migration?

### ISSUE THREAD

**Issue by tedfernandess** [xmunoz/bugzilla2gitlab#13]
Hi guys,

I have installed everything with success.
I have a clean Gitlab installation with one project.
I also have a bugzilla running.

I have created bugs on bugzilla. I want to migrate them to Gitlab follow your instructions.

I am trying to execute with the virtual env activated, and inside the bugzilla2gitlab:

bin/bugzilla2gitlab [-h] myfile.txt

and it returns the following output:

**Traceback (most recent call last):
  File "bin/bugzilla2gitlab", line 26, in <module>
    main()
  File "bin/bugzilla2gitlab", line 19, in main
    with open(args.bug_list, "r") as f:
IOError: [Errno 2] No such file or directory: '[-h]'**

But the file is inside the project. on the same place that I am running the command

When I try to pass all the parameters like: bin/bugzilla2gitlab [-h] file.txt config:

usage: bugzilla2gitlab [-h] [FILE] [CONFIG_DIRECTORY]
bugzilla2gitlab: error: unrecognized arguments: config

But the directory exists and is on the same place that I am running the command too.

I already configure my yml files on the config directory.
Please, help

**Comment by xmunoz** [comment]
`-h` is the help flag, which displays information about how to use the library. If you don't need help, and simply want to run the library, then the command is:

```
bin/bugzilla2gitlab buglistfile configdirectory
```
