### ISSUE TITLE
Does not work without GitLab sudo

### ISSUE THREAD

**Issue by link2xt** [xmunoz/bugzilla2gitlab#16]
bugzilla2gitlab requires [sudo](http://doc.gitlab.com/ce/api/#sudo). As a result, it is only possible to use on own GitLab installations, but not https://gitlab.com/

The first POST request to `https://gitlab.com/api/v4/projects/[gitlab_project_id]/issues` fails with
```
{'message': '403 Forbidden  - Must be admin to use sudo'}
```

It is ok for me if all issues and comments appear to be posted by "bot" account, but it seems bugzilla2gitlab does not work this way even if I map all users in `user_mappings.yml` to my account.

**Comment by xmunoz** [comment]
Yeah, it would be a bit of a change to introduce this functionality. Feel free to send along a PR!
