### ISSUE TITLE
Descriptions in GitLab import as 1 letter per line.

### ISSUE THREAD

**Issue by dariorazum** [xmunoz/bugzilla2gitlab#18]
After using bugzilla2gitlab, the resulting GitLab issue has a weird bug where the descriptions end up writing vertically. Basically it puts one letter per line and so forth. E.G: The word 'welcome' for example would look like this:

w
e
l
c
o
m
e

**Comment by xmunoz** [comment]
Yeah, you will probably need to hack on `create_description` in models.py a bit to get something that works for your bugzilla/gitlab. Let me know how it goes, and feel free to send along a pull request!
