### ISSUE TITLE
Is it possible to use the original bug id as issue id?

### ISSUE THREAD

**Issue by abbbi** [xmunoz/bugzilla2gitlab#27]
hi,

short question: is it possible to migrate the bugs "as is", means sepzilla bug id 10 will become issue #10 in gitlab? 
Or is there a limitation on gitlab api site? Providing the tool with a list seems to re-number the issues (starting from 1)?

**Comment by xmunoz** [comment]
No, there is no way to control the gitlab issue number from the API.

**Comment by abbbi** [comment]
hi,


> No, there is no way to control the gitlab issue number from the API.

i think it works with the latest version. An "iid" parameter was created which allows to do so, example:

`curl -k --request POST --header "PRIVATE-TOKEN:token" "https://srv/api/v4/projects/2/issues?title=Issues%20with%20auth&labels=bug&iid=30`

the api will end up creating issue with id #30 instead of re-numbering

**Comment by xmunoz** [comment]
Ah, I see: https://docs.gitlab.com/ee/api/issues.html#new-issue

When I wrote this several years ago it was using v1 of the API. I have not done any major upgrades since. That said, feel free to send a PR along that adds support for this.

**Comment by abbbi** [comment]
Unfortunately its a bit more complicated. It seems iid is ignored if sudo is set during post request. The API is still auto-assigning issue ids then. Removing the sudo flag during issue creation it works with preset id :/

**Comment by xmunoz** [comment]
Fixed by #28
